---
title: "Client Report - What is in a Name?"
subtitle: "Course DS 250"
author: "Gabriel Guerrero"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

### Background

Early in prehistory, some descriptive names began to be used again and again until they formed a name pool for a particular culture. Parents would choose names from the pool of existing names rather than invent new ones for their children.

With the rise of Christianity, certain trends in naming practices manifested. Christians were encouraged to name their children after saints and martyrs of the church. These early Christian names can be found in many cultures today, in various forms. These were spread by early missionaries throughout the Mediterranean basin and Europe.

By the Middle Ages, the Christian influence on naming practices was pervasive. Each culture had its pool of names, which were a combination of native names and early Christian names that had been in the language long enough to be considered native.

### Libraries and Tide Data
```{python}
#| label: libraries
#| include: true


import pandas as pd
import numpy as np
import plotly.express as px
from lets_plot import *
LetsPlot.setup_html()
from datetime import datetime

```

```{python}
#| label: project-data
#| code-summary: Load the data


# data in local file
#df = pd.read_csv(r"C:\Users\Gabriel Guerrero\OneDrive - AVASA\BYU-I\DS 250 Data Coding\db-projects\names_year.csv")



df = pd.read_csv('https://raw.githubusercontent.com/byuidatascience/data4names/refs/heads/master/data-raw/names_year/names_year.csv')

#local
#r"C:\Users\Gabriel Guerrero\OneDrive - AVASA\BYU-I\DS 250 Data Coding\db-projects\names_year.csv"

#online
#https://raw.githubusercontent.com/byuidatascience/data4names/refs/heads/master/data-raw/names_year/names_year.csv'

```
```{python}
#| label: Describe
#| code-summary: Tide data
#| include: false

df.describe()
df.tail(10)

```

```{python}
#| code-summary: Tiding 1
#| echo: true

# check for missing and na values

df.isna()
df.isnull()
df.dropna(inplace=True)


```

```{python}
#| code-summary: Tide data 2
#| echo: true
# group df by name and summarize

df_grouped = df.groupby(['name', 'year']).agg(total=('Total', 'sum')).reset_index()
#df_grouped.head(10)
```
### Elevator pitch
This project aims to explore understand the use of a name over time. The use of group funtion and sum will be used to show the use of a name over time.

### Requirements
For Project 1 the answer to each question should include a `chart` and a `written response`. The years labels on your charts should not include a comma. At least two of your charts must include reference marks.

### Question 1: 
**How does your name at your birth year compare to its use historically?**

This following graph show that my name has increased its used over the years from less than a 1000 to more than 10000 in 40 years.

```{python}
#| label: Q1-chart
#| code-summary: Plot 1
#| fig-cap: "Source: Names from years csv"
#| fig-align: center

df_grouped1= df_grouped[df_grouped['name'] == 'Gabriel']
import numpy as np
trend_text='Incresing accerelating \n after 1980'

(
  ggplot(df_grouped1, aes(x='year', y='total', color='name')) +
    geom_line(color='blue') + 
    geom_point(color='blue') +
    labs(title='Names from 1900 to 2022',
         subtitle='Use of Gabriel is increasing', 
         x='Year', 
         y='Total Numbers') +
    theme_bw() +  # Base theme
    # Customized x-axis
    scale_x_continuous(breaks=np.arange(1900, 2030, 20).astype(int),  
                       limits=(1900, 2020)) +  # Set start and end for x-axis
    # Customized y-axis
    scale_y_continuous(breaks=np.arange(0, int(df_grouped1['total'].max()) + 1, 2000), 
                       limits=(0, int(df_grouped1['total'].max()))) +  # Set start and end for y-axis
    # Title and subtitle styling
    theme(plot_title=element_text(color='black', size=18, face='bold'),
          plot_subtitle=element_text(color='Blue', size=14, face='italic'))+ # Subtitle styling+
    geom_label(x=1980, y=6000, label=trend_text, color="black", size='6', fill='#D3D3D3')
)



```


### Question 2: 
**If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?**

Based on the graph, I would guess that I will be taking to a person betweeen 20 and 30 years old. I would not guess that I will be talking to a person over 40 years old and lest than 10 years old.

```{python}
#| label: Q2-chart
#| code-summary: Plot 2
#| fig-cap: "Source: Names from years csv"
#| fig-align: center


today = datetime.now()  # Get the current date and time
trend_text = "Concentration of Brittany  \n between 80 and 90"

# Calculate the actual year difference

df['actual_year'] = today.year - df['year']
df2 = df[df['name']=='Brittany']  

'''
df_grouped2 = df2.groupby(['name', 'year']).agg(
    Total=('Total', 'sum'),
    Age=('actual_year', 'mean')
).reset_index()
'''
#keeping name, year
df2 = df2[['name', 'year', 'Total', 'actual_year']]
(
  ggplot(df2, aes(x='year', y='actual_year', size='Total')) +
    geom_line(color='black') + 
    geom_point(color='#103d85') +
    labs(title='Use of the name Brittany from 1960 to 2010',
         subtitle='80 and 90 has more density', 
         x='Year', 
         y='Total Numbers') +
    theme_bw() +  # Base theme
    # Customized x-axis
    scale_x_continuous(breaks=np.arange(1960, 2018, 10).astype(int),  
                       limits=(1960, 2020)) +  # Set start and end for x-axis
    # Customized y-axis
    scale_y_continuous(breaks=np.arange(0, int(df2['actual_year'].max()) + 1, 10), 
                       limits=(0, int(df2['actual_year'].max()))) +  # Set start and end for y-axis
    # Title and subtitle styling
    theme(plot_title=element_text(color='black', size=18, face='bold'),
          plot_subtitle=element_text(color='#4287f5', size=14, face='italic')
          )  # Subtitle styling
    # Adding a label 
    +geom_label(x=2005, y=40, label=trend_text, color="black", size='6', fill='#D3D3D3')
    #geom_text(data=last_points, aes(x='year', y='total', label=name))
  



)


```


### Question 3: 
**Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names in a single chart. What trends do you notice?**

The trend indicates that the use of names of Mary and Paul have declined over the years more than Martha and Peter.

```{python}
#| label: Q3-chart
#| code-summary: Plot 3
#| fig-cap: "Source: Names from years csv"
#| fig-align: center

df_grouped3 = df_grouped[df_grouped['name'].isin(['Mary', 'Martha', 'Peter', 'Paul'])]

#Checking the unique names
# df_grouped3['name'].unique()

# Define your label text
trend_text = "Significant decline \nafter 2,000"
last_points = df_grouped3.groupby('name').last().reset_index()

(
    ggplot(df_grouped3, aes(x='year', y='total', color='name')) +  # Color by 'name'
    geom_line() +
    geom_line(aes(size=(df_grouped3['name'].map({'Mary': 2, 'Martha': 1, 'Peter': 1, 'Paul': 2})))) +
    labs(title='Selected Names Analysis',
         subtitle='Mary, Martha, Peter, Paul through the years', 
         x='Year', 
         y='Total Numbers') +
      # Base theme
    theme_bw() +
    # Customized x-axis
    scale_x_continuous(breaks=np.arange(1970, 2020, 10).astype(int),  
                       limits=(1970, 2015)) +  # Set start and end for x-axis
    # Customized y-axis
    scale_y_continuous(breaks=np.arange(0, int(df_grouped3['total'].max()) + 1, 5000), 
                       limits=(0, 20000)) +  # Set start and end for y-axis
    # Title and subtitle styling
   theme(
        plot_title=element_text(color='black', size=20, face='bold'),
        plot_subtitle=element_text(color='#4287f5', size=16, face='regular'),
        #legend_position="none"  # Remove legends,
    ) +
    # Adding a label 
    geom_label(x=2005, y=8000, label=trend_text, color="black", size='6',  fill='#D3D3D3')  
  
)

```

### Question 4: 
**Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?**

I picked the name Olivia for actress of the movie "Grease". The movie was released in 1978. The usage of the name Olivia increased after the movie was released aroudn 1990.

```{python}

#| label: Q4-chart
#| code-summary: Plot 4
#| fig-cap: "Source: Names from years csv"
#| fig-align: center

df_grouped4 = df_grouped[df_grouped['name'].isin(['Olivia'])]

(
    ggplot(df_grouped4, aes(x='year', y='total', color='name')) +  # Color by 'name'
    geom_line()+
     labs(title='Unique name from a famous movie Analysis',
         subtitle='Movie Grease released in 1990', 
         x='Year', 
         y='Total Numbers') +
      # Base theme
    theme_classic() +
    # Customized x-axis
    scale_x_continuous(breaks=np.arange(1970, 2020, 10).astype(int),  
                       limits=(1970, 2015)) +  # Set start and end for x-axis
    # Customized y-axis
    scale_y_continuous(breaks=np.arange(0, int(df_grouped3['total'].max()) + 1, 5000), 
                       limits=(0, 20000)) +  # Set start and end for y-axis
    # Title and subtitle styling
   theme(
        plot_title=element_text(color='black', size=20, face='bold'),
        plot_subtitle=element_text(color='#4287f5', size=16, face='regular'),
        #legend_position="none"  # Remove legends,
    ) +
    # Adding a label 
    geom_label(x=2005, y=8000, label="Olivia has increased \nafter 1990", color="black", size='6',  fill='#D3D3D3')   

)
```



```{python}
#| include: false

#Question 1
df_grouped10 = df[(df['name'] == 'Oliver') & (df['UT'] >= 1)][['name', 'UT']]

df_grouped10['UT'].sum()


```

```{python}

#| include: false

#Question 2
dfq= df[(df['name'] == 'Felisha')]
dfq= dfq.groupby(['year'])
dfq.head(5)

```

```{python}
#| include: false

#Question 3
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=['a', 'b', 'c'])
df = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]}) 
```